/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.view.menu.sp;

import aplikasi.config.FieldLimit;
import aplikasi.config.FieldMinimal;
import aplikasi.config.KoneksiDB;
import aplikasi.config.ValueFormatter;
import aplikasi.entity.Penduduk;
import aplikasi.entity.SuratPengantar;
import aplikasi.entity.Users;
import aplikasi.service.ServicePenduduk;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import aplikasi.repository.RepoPenduduk;
import aplikasi.service.ServiceSp;
import java.sql.Date;
import java.util.Iterator;
import aplikasi.repository.RepoSp;

/**
 *
 * @author niser
 */
public class DataSpView extends javax.swing.JDialog {

    private Boolean update;

    private final RepoPenduduk repoPenduduk = new ServicePenduduk(KoneksiDB.getDataSource());
    private final RepoSp repoKtp = new ServiceSp(KoneksiDB.getDataSource());

    private DaftarSpView daftarSpController = null;
    private Penduduk penduduk;
    private SuratPengantar suratPengantar;
    private FieldMinimal jTextFieldMinimal;
    private Users p = null;

    public Boolean isUpdate() {
        return update;
    }

    public void setUpdate(Boolean update) {
        this.update = update;
    }

    /**
     * Creates new form DataView
     */
    public DataSpView(java.awt.Frame parent, boolean modal, Users p) {
        super(parent, modal);
        initComponents();
        setUpdate(false);
        this.daftarSpController = null;
        this.penduduk = new Penduduk();
        this.suratPengantar = new SuratPengantar();
        this.p = p;
        this.jTextFieldMinimal = new FieldMinimal();
        this.txtTglPengajuan.setDate(new java.util.Date());
        txtNama.requestFocus();
//        ambilKode();
        textFieldLimit();
    }

    DataSpView(java.awt.Frame parent, DaftarSpView daftarSpController, boolean modal, Users p) {
        super(parent, modal);
        initComponents();
        setUpdate(false);
        this.daftarSpController = daftarSpController;
        this.penduduk = new Penduduk();
        this.suratPengantar = new SuratPengantar();
        this.p = p;
        this.jTextFieldMinimal = new FieldMinimal();
        this.txtTglPengajuan.setDate(new java.util.Date());
        txtNoSp.requestFocus();
    }

    DataSpView(java.awt.Frame parent, DaftarSpView daftarSpController, SuratPengantar ktp, boolean modal, Users p) {
        super(parent, modal);
        initComponents();
        setUpdate(true);
        this.daftarSpController = daftarSpController;
        this.penduduk = new Penduduk();
        this.suratPengantar = new SuratPengantar();
        this.p = p;
        this.jTextFieldMinimal = new FieldMinimal();
        this.txtTglPengajuan.setDate(new java.util.Date());
        txtNoSp.setEditable(false);
        txtNik.requestFocus();
        if (ktp.getKeperluan().equals(rbKeperluanKtp.getText())) {
            rbKeperluanKtp.setSelected(true);
        }else if(ktp.getKeperluan().equals(rbKeperluanKK.getText())){
            rbKeperluanKK.setSelected(true);
        }else {
            rbKeperluanLLN.setSelected(true);
            txtKeperluan.setEditable(true);
            txtKeperluan.setText(ktp.getKeperluan());
            txtKeperluan.requestFocus();
        }
        
        textFieldLimit();
        setFieldsKtp(ktp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminGroup = new javax.swing.ButtonGroup();
        JenisWNGroup = new javax.swing.ButtonGroup();
        jenisKeperluanGroup = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnSimpan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNik = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTempatLahir = new javax.swing.JTextField();
        txtTglLahir = new javax.swing.JTextField();
        txtKelamin = new javax.swing.JTextField();
        txtNamaIbu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTglPengajuan = new com.toedter.calendar.JDateChooser();
        txtNoSp = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        rbKeperluanKtp = new javax.swing.JRadioButton();
        rbKeperluanKK = new javax.swing.JRadioButton();
        rbKeperluanLLN = new javax.swing.JRadioButton();
        txtKeperluan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data KTP");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo3.png")).getImage());

        jToolBar1.setRollover(true);

        btnSimpan.setText("Simpan");
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSimpan.setMaximumSize(new java.awt.Dimension(120, 35));
        btnSimpan.setMinimumSize(new java.awt.Dimension(120, 35));
        btnSimpan.setPreferredSize(new java.awt.Dimension(120, 35));
        btnSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });
        jToolBar1.add(btnSimpan);

        btnKembali.setText("Kembali");
        btnKembali.setFocusable(false);
        btnKembali.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKembali.setMaximumSize(new java.awt.Dimension(120, 35));
        btnKembali.setMinimumSize(new java.awt.Dimension(120, 35));
        btnKembali.setPreferredSize(new java.awt.Dimension(120, 35));
        btnKembali.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKembali);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        jPanel1.setToolTipText("");

        jLabel1.setText("No SP");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setText("Nama");

        jLabel8.setText("Nama Ibu");

        jLabel9.setText("Tempat Lahir");

        jLabel10.setText("Tanggal Lahir");

        jLabel11.setText("Kelamin");

        jLabel5.setText("Nik");

        txtNik.setToolTipText("");
        txtNik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNikKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNikKeyReleased(evt);
            }
        });

        txtNama.setEditable(false);
        txtNama.setToolTipText("");
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaKeyReleased(evt);
            }
        });

        txtTempatLahir.setEditable(false);
        txtTempatLahir.setToolTipText("");
        txtTempatLahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTempatLahirKeyReleased(evt);
            }
        });

        txtTglLahir.setEditable(false);
        txtTglLahir.setToolTipText("");
        txtTglLahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTglLahirKeyReleased(evt);
            }
        });

        txtKelamin.setEditable(false);
        txtKelamin.setToolTipText("");
        txtKelamin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKelaminKeyReleased(evt);
            }
        });

        txtNamaIbu.setEditable(false);
        txtNamaIbu.setToolTipText("");
        txtNamaIbu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaIbuKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(txtNamaIbu)
                    .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKelamin, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(txtTglLahir))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNik, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaIbu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTempatLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTglLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setText("Tanggal Pengajuan");

        txtNoSp.setToolTipText("");
        txtNoSp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoSpKeyReleased(evt);
            }
        });

        jLabel21.setText("Keperluan");

        jenisKeperluanGroup.add(rbKeperluanKtp);
        rbKeperluanKtp.setText("Pengurusan KTP");

        jenisKeperluanGroup.add(rbKeperluanKK);
        rbKeperluanKK.setText("Pengurusan Kartu Keluarga");
        rbKeperluanKK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbKeperluanKKFocusGained(evt);
            }
        });
        rbKeperluanKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKeperluanKKActionPerformed(evt);
            }
        });

        jenisKeperluanGroup.add(rbKeperluanLLN);
        rbKeperluanLLN.setText("LLN");
        rbKeperluanLLN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbKeperluanLLNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rbKeperluanLLNFocusLost(evt);
            }
        });

        txtKeperluan.setEditable(false);
        txtKeperluan.setToolTipText("");
        txtKeperluan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeperluanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKeperluanKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTglPengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoSp, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbKeperluanKK)
                                    .addComponent(rbKeperluanKtp)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbKeperluanLLN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKeperluan, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNoSp)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTglPengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbKeperluanKtp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbKeperluanKK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbKeperluanLLN)
                    .addComponent(txtKeperluan, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void textFieldLimit() {
        txtNama.setDocument(new FieldLimit(50));
    }

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        suratPengantar.setNo_sp(txtNoSp.getText());
        suratPengantar.setTgl(Date.valueOf(ValueFormatter.getDateSQL(txtTglPengajuan.getDate())));
        penduduk.setNik(txtNik.getText());
        suratPengantar.setPenduduk(penduduk);
        if (rbKeperluanKtp.isSelected()) {
            suratPengantar.setKeperluan(rbKeperluanKtp.getText());
        }else if(rbKeperluanKK.isSelected()){
            suratPengantar.setKeperluan(rbKeperluanKK.getText());
        } else {
            suratPengantar.setKeperluan(txtKeperluan.getText());
        }

        if (isUpdate()) {
            try {
                repoKtp.update(suratPengantar);
                this.dispose();
                if (daftarSpController != null) {
                    daftarSpController.refreshDataTables();
//                    daftarSpController.setFields(ktp);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Tidak dapat merubah data barang", getTitle(), JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(DataSpView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                repoKtp.save(suratPengantar);
                if (daftarSpController != null) {
                    daftarSpController.refreshDataTables();
//                    daftarSpController.setFields(ktp);
                    daftarSpController.selectLastRow();
                    daftarSpController.btnTambahRequesFocus();
                }
                this.dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan data barang baru", getTitle(), JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(DataSpView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnSimpanActionPerformed
    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSimpanActionPerformed(null);
        }
    }//GEN-LAST:event_btnSimpanKeyPressed

    private void txtNikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNikKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNikKeyReleased

    private void txtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKeyReleased

    private void txtTempatLahirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempatLahirKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempatLahirKeyReleased

    private void txtTglLahirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTglLahirKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglLahirKeyReleased

    private void txtKelaminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKelaminKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelaminKeyReleased

    private void txtNoSpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoSpKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoSpKeyReleased

    private void txtNamaIbuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaIbuKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaIbuKeyReleased

    private void txtNikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNikKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                for (Iterator<Penduduk> it = repoPenduduk.findByNik(txtNik.getText()).iterator(); it.hasNext();) {
                    Penduduk a = it.next();
                    a.getNik();
                    a.getNama();
                    a.getNama_ibu();
                    a.getNama_ayah();
                    a.getTmp_lahir();
                    a.getTgl_lahir();
                    a.getKelamin();
                    a.getGol_darah();
                    a.getAlamat();
                    a.getRt();
                    a.getRw();
                    a.getKelurahan();
                    a.getKecamatan();
                    a.getAgama();
                    a.getPendidikan();
                    a.getSts_kawin();
                    a.getPekerjaan();
                    a.getKewarganegaraan();
                    setFields(a);
                }

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_txtNikKeyPressed

    private void txtKeperluanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeperluanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeperluanKeyPressed

    private void txtKeperluanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeperluanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeperluanKeyReleased

    private void rbKeperluanKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKeperluanKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbKeperluanKKActionPerformed

    private void rbKeperluanLLNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbKeperluanLLNFocusGained
        txtKeperluan.setEditable(true);
        txtKeperluan.requestFocus();

    }//GEN-LAST:event_rbKeperluanLLNFocusGained

    private void rbKeperluanLLNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbKeperluanLLNFocusLost
//        txtKeperluan.setEditable(false);
//        txtKeperluan.setEditable(true);
    }//GEN-LAST:event_rbKeperluanLLNFocusLost

    private void rbKeperluanKKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbKeperluanKKFocusGained
                txtKeperluan.setText("");
        txtKeperluan.setEditable(false);
    }//GEN-LAST:event_rbKeperluanKKFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JenisWNGroup;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.ButtonGroup jenisKelaminGroup;
    private javax.swing.ButtonGroup jenisKeperluanGroup;
    private javax.swing.JRadioButton rbKeperluanKK;
    private javax.swing.JRadioButton rbKeperluanKtp;
    private javax.swing.JRadioButton rbKeperluanLLN;
    private javax.swing.JTextField txtKelamin;
    private javax.swing.JTextField txtKeperluan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaIbu;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNoSp;
    private javax.swing.JTextField txtTempatLahir;
    private javax.swing.JTextField txtTglLahir;
    private com.toedter.calendar.JDateChooser txtTglPengajuan;
    // End of variables declaration//GEN-END:variables


    private void setFields(Penduduk p) {
        txtNama.setText(p.getNama());
        txtNamaIbu.setText(p.getNama_ibu());
        txtTempatLahir.setText(p.getTmp_lahir());
        txtTglLahir.setText(p.getTgl_lahir().toString());
        txtKelamin.setText(p.getRt());
    }

//    private void ambilKode() {
//        try {
//            String s = null;
//            StringBuilder sb = new StringBuilder("MD").append("-");
//            List<Penduduk> daftarPenduduk = repoPenduduk.findMaxValue();
//            if (!daftarPenduduk.isEmpty()) {
//                for (Penduduk penduduk1 : daftarPenduduk) {
//                    s = penduduk1.getNik();
//                }
//                String s2 = s.substring(3);
//                int s3 = Integer.valueOf(s2) + 1;
//                sb.append(String.format("%04d", s3));
//                this.penduduk.setNik(sb.toString());
//                txtKode.setText(this.penduduk.getNik());
//            } else {
//                this.penduduk.setNik("MD-0001");
//                txtKode.setText(this.penduduk.getNik());
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this, "Tidak dapat mendapatkan kode!", getTitle(), JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(DataSpView.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    private void setFieldsKtp(SuratPengantar ktp) {
        txtNoSp.setText(ktp.getNo_sp());
        txtNik.setText(ktp.getPenduduk().getNik());
    }
}
